name: Node.js CI with Docker Build and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DOCKER_IMAGE: "hamster_dev"
  DEPLOY_DIR: "/root/deploy/"
  CONTAINER_NAME: "hamster_dev"
  HOST_PORT: "3003"
  CONTAINER_PORT: "3003"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]  # Используйте стабильную версию Node.js

    steps:
      - uses: actions/checkout@v4

      - name: Clean and reinstall dependencies
        run: |
          rm -rf node_modules package-lock.json
          npm install --legacy-peer-deps

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: npm run build --if-present

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t $DOCKER_IMAGE .
          docker images

      - name: Save Docker image
        run: |
          docker save $DOCKER_IMAGE -o $DOCKER_IMAGE.tar
          ls -lh

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: deployment-files
          path: |
            ${{ env.DOCKER_IMAGE }}.tar
            docker-compose.yml

  deploy-to-server:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: deployment-files
          path: .

      - name: List downloaded files
        run: |
          ls -la

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H "${{ secrets.SERVER_IP }}" >> ~/.ssh/known_hosts

      - name: Create deploy directory on remote server
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_ed25519 ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "
            echo '${{ secrets.SUDO_PASSWORD }}' | sudo -S mkdir -p $DEPLOY_DIR &&
            echo '${{ secrets.SUDO_PASSWORD }}' | sudo -S chown ${{ secrets.SERVER_USER }}:${{ secrets.SERVER_USER }} $DEPLOY_DIR &&
            echo '${{ secrets.SUDO_PASSWORD }}' | sudo -S chmod 777 $DEPLOY_DIR
          "

      - name: Check for required files
        run: |
          if [ ! -f "$DOCKER_IMAGE.tar" ]; then
            echo "Error: $DOCKER_IMAGE.tar not found!"
            exit 1
          fi
          if [ ! -f "docker-compose.yml" ]; then
            echo "Error: docker-compose.yml not found!"
            exit 1
          fi

      - name: Copy files to remote server
        run: |
          scp -o StrictHostKeyChecking=no -i ~/.ssh/id_ed25519 $DOCKER_IMAGE.tar ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:$DEPLOY_DIR
          scp -o StrictHostKeyChecking=no -i ~/.ssh/id_ed25519 docker-compose.yml ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:$DEPLOY_DIR

      - name: Deploy Docker image on remote server
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_ed25519 ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "
            cd $DEPLOY_DIR &&
            echo '${{ secrets.SUDO_PASSWORD }}' | sudo -S docker load -i $DOCKER_IMAGE.tar &&
            echo '${{ secrets.SUDO_PASSWORD }}' | sudo -S docker compose down &&
            echo '${{ secrets.SUDO_PASSWORD }}' | sudo -S docker compose up -d
          "